stages:
  - quality

code-quality:
  stage: quality
  image: nikolaik/python-nodejs:python3.13-nodejs22
  cache:
    key: pip-$CI_COMMIT_REF_SLUG
    paths:
      - .pip-cache
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  before_script:
    - pip install --upgrade pip
    - pip install tox
  script:
    - tox -e all
